const STREAM_SUBJECTS = {
  "CSE": [
    "Data Structures & Algorithms",
    "Database Management Systems",
    "Operating Systems",
    "Computer Networks",
    "Object Oriented Programming",
    "Software Engineering",
  ],
  "AIDS": [
    "Data Structures & Algorithms",
    "Machine Learning",
    "Statistics for Data Science",
    "Python Programming",
    "Database Management Systems",
    "Big Data Analytics",
  ],
  "AI & Robotics": [
    "Robotics Fundamentals",
    "Machine Learning",
    "Embedded Systems",
    "Control Systems",
    "Computer Vision",
    "Sensors & Actuators",
  ],
  "AIML": [
    "Machine Learning",
    "Deep Learning",
    "Data Structures & Algorithms",
    "Python Programming",
    "Neural Networks",
    "Natural Language Processing",
  ],
  "BCA": [
    "Programming in C",
    "Data Structures",
    "Database Management Systems",
    "Web Technologies",
    "Computer Networks",
    "Operating Systems",
  ],
  "BA": [
    "English Literature",
    "History",
    "Political Science",
    "Sociology",
    "Economics",
    "Psychology",
  ],
  "BBA": [
    "Principles of Management",
    "Business Economics",
    "Financial Accounting",
    "Marketing Management",
    "Business Communication",
    "Organizational Behavior",
  ],
  "B.Com": [
    "Financial Accounting",
    "Business Law",
    "Economics",
    "Income Tax",
    "Business Statistics",
    "Corporate Accounting",
  ],
  "BSc": [
    "Physics",
    "Chemistry",
    "Mathematics",
    "Botany",
    "Zoology",
    "Environmental Science",
  ],
  "Mechanical": [
    "Engineering Mechanics",
    "Thermodynamics",
    "Fluid Mechanics",
    "Strength of Materials",
    "Manufacturing Processes",
    "Machine Design",
  ],
};

module.exports = { STREAM_SUBJECTS };